services:

  mysql:
    image: mysql:8.0
    container_name: employee-mysql
    environment:
      MYSQL_DATABASE: employee_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
      MYSQL_ROOT_PASSWORD: root123
    volumes:
      - employee_mysql_data:/var/lib/mysql

  employee-app:
    image: akashms54/employee-app:latest
    container_name: employee-app
    ports:
      - "8085:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/employee_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
    depends_on:
      - mysql

volumes:
  employee_mysql_data:
